services:
  mb-nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules